config/routes.rb
Rails.application.routes.draw do
  root 'products_shops#select_city'
  resources :products_shops, only: :index do
    collection do
      get 'select_city'
      get 'get_list'
    end
  end

end

app/models/city.rb
class City < ActiveRecord::Base
  has_many :shops

  validates :name, presence: true
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :products_shops
  has_many :shops, through: :products_shops

  validates :name, :color, presence: true
  validates :item_number, :weight, :size, numericality: { greater_than: 0 }
end

app/models/products_shop.rb
class ProductsShop < ActiveRecord::Base
  belongs_to :shop
  belongs_to :product

  validates :cost, :quantity, numericality: { greater_than: 0 }
  validates :shop, :product, presence: true

  PROPS = {
    product_name: "Название товара",
           cost: "Цена",
           city: "Город",
           address: "Адрес",
           subway: "Метро",
           size: "Размер",
           weight: "Вес"
  }.freeze
end

app/models/shop.rb
class Shop < ActiveRecord::Base
  belongs_to :city
  has_many :products_shops
  has_many :products, through: :products_shops

  validates :name, :address, :city, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/products_shops_controller.rb
class ProductsShopsController < ApplicationController
  def select_city
    session[:city_ids] = nil
    @cities = City.order(:name)
    if params[:form]
      city_ids = params[:city_ids]
      if city_ids
        session[:city_ids] = city_ids
        redirect_to "/products_shops/get_list"
      else
        redirect_to "/products_shops/select_city",
                    alert: 'Не выбран город.'
      end
    end
  end

  def get_list
    city_ids = session[:city_ids]
    @shops = Shop.where(city_id: city_ids).eager_load(:city).order('cities.name', :name, :address)
    shop_ids = params[:shop_ids]
    props = params[:props]
    if params[:form] && !shop_ids
      redirect_to "/products_shops/get_list",
                  alert: 'Выберите один или несколько магазинов для формирования отчета.'
    end
    @products_list = ProductsShop::PrepareList.call(shop_ids, props) if shop_ids && shop_ids.any?
    respond_to do |format|
      format.xlsx {
        response.headers[
          'Content-Disposition'
        ] = "attachment; filename='Отчет_по_остаткам.xlsx'"
      }
      format.html
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>OnlineShop</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<p class="alert"><%= alert %></p>

<%= yield %>

</body>
</html>

app/views/products_shops/get_list.html.slim
- shops_length = @shops.length
- number_rows = (shops_length.to_f / 3).ceil
h2 Отчет по остаткам
= form_tag get_list_products_shops_path(format: :xlsx), method: :get do |f|
  = hidden_field_tag "form", :true
  h3 Дополнительные поля отчета
  - ProductsShop::PROPS.each_pair do |prop, prop_name|
    p
      = label_tag(prop_name)
      = check_box_tag( {:multiple => true}, prop, nil, name:"props[]")
  h3 Магазины
  - (0..number_rows - 1).each do |row|
    table
      tr
        - (0..3).each do |col|
          td
            - shop_ind = row + number_rows * col
            - if shop_ind < shops_length
              - shop = @shops[shop_ind]
              - shop_full = "#{shop.name}, #{shop.city.name}, #{shop.address}"
              - shop_full += ", метро: #{shop.subway}" if shop.subway
              = check_box_tag( {:multiple => true}, shop.id, nil, name:"shop_ids[]")
              = label_tag(shop_full)
  p = submit_tag "Сформировать"

  p = link_to "Вернуться к выбору городов", select_city_products_shops_path

app/views/products_shops/select_city.html.slim
  h3 Выберите один или несколько городов для формирования отчета.
  = form_tag select_city_products_shops_path, method: :get do |f|  
    - @cities.each do |city|
      p
        = hidden_field_tag "form", :true    
        = label_tag(city.name)
        = check_box_tag( {:multiple => true}, city.id, nil, name:"city_ids[]")
    p = submit_tag "Далее"